import * as XLSX from "xlsx";
import fs from "fs";
import { webcrypto } from "node:crypto";
if (!globalThis.crypto) globalThis.crypto = webcrypto;
const { detectTabbyHeaderRow, autoMapTabby, checkTabbyStructure, buildTabbyRows, groupTabbyLines, computeTabbyFileTotals } = await import("/dev-server/src/lib/finance/tabby-import.ts");
const buf = fs.readFileSync("/tmp/tabby.csv");
const wb = XLSX.read(buf, { type: "buffer", cellDates: true });
const ws = wb.Sheets[wb.SheetNames[0]];
const aoa = XLSX.utils.sheet_to_json(ws, { header: 1, defval: null, raw: true });
const hr = detectTabbyHeaderRow(aoa);
const headers = aoa[hr];
console.log("header row idx:", hr);
console.log("headers:", headers);
console.log("structure:", checkTabbyStructure(headers));
const mapping = autoMapTabby(headers);
console.log("mapping:", mapping);
const lines = await buildTabbyRows(aoa, hr, mapping);
const groups = groupTabbyLines(lines);
const totals = computeTabbyFileTotals(lines, groups);
console.log("lines:", lines.length);
console.log("groups:", groups.length);
console.log("totals:", totals);
console.log("first group:", groups[0]);
console.log("needs_review sample:", lines.filter(l=>l.needs_review).slice(0,3));
