/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BusinessSolutionsRouteImport } from './routes/business-solutions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ServicesCustomAquariumsRouteImport } from './routes/services.custom-aquariums'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminTanksRouteImport } from './routes/_authenticated/admin.tanks'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProjectCategoriesRouteImport } from './routes/_authenticated/admin.project-categories'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminDesignRouteImport } from './routes/_authenticated/admin.design'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAccountRequestsRouteImport } from './routes/_authenticated/account.requests'
import { Route as AuthenticatedAccountReportsRouteImport } from './routes/_authenticated/account.reports'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account.notifications'
import { Route as AuthenticatedAccountAppointmentsRouteImport } from './routes/_authenticated/account.appointments'
import { Route as AuthenticatedAdminRequestsIndexRouteImport } from './routes/_authenticated/admin.requests.index'
import { Route as AuthenticatedAdminGalleryIndexRouteImport } from './routes/_authenticated/admin.gallery.index'
import { Route as AuthenticatedAdminFinanceIndexRouteImport } from './routes/_authenticated/admin.finance.index'
import { Route as AuthenticatedAdminDesignIndexRouteImport } from './routes/_authenticated/admin.design.index'
import { Route as AuthenticatedAccountTanksIndexRouteImport } from './routes/_authenticated/account.tanks.index'
import { Route as AuthenticatedAccountRequestsIndexRouteImport } from './routes/_authenticated/account.requests.index'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminTanksIdRouteImport } from './routes/_authenticated/admin.tanks.$id'
import { Route as AuthenticatedAdminRequestsIdRouteImport } from './routes/_authenticated/admin.requests.$id'
import { Route as AuthenticatedAdminFinanceSuppliersRouteImport } from './routes/_authenticated/admin.finance.suppliers'
import { Route as AuthenticatedAdminFinanceSettingsRouteImport } from './routes/_authenticated/admin.finance.settings'
import { Route as AuthenticatedAdminFinanceIncomesRouteImport } from './routes/_authenticated/admin.finance.incomes'
import { Route as AuthenticatedAdminFinanceExportRouteImport } from './routes/_authenticated/admin.finance.export'
import { Route as AuthenticatedAdminFinanceExpensesRouteImport } from './routes/_authenticated/admin.finance.expenses'
import { Route as AuthenticatedAdminFinanceCategoriesRouteImport } from './routes/_authenticated/admin.finance.categories'
import { Route as AuthenticatedAdminFinanceAuditRouteImport } from './routes/_authenticated/admin.finance.audit'
import { Route as AuthenticatedAdminFinanceAttachmentsRouteImport } from './routes/_authenticated/admin.finance.attachments'
import { Route as AuthenticatedAdminDesignContactRouteImport } from './routes/_authenticated/admin.design.contact'
import { Route as AuthenticatedAdminDesignAboutRouteImport } from './routes/_authenticated/admin.design.about'
import { Route as AuthenticatedAccountTanksIdRouteImport } from './routes/_authenticated/account.tanks.$id'
import { Route as AuthenticatedAccountRequestsNewRouteImport } from './routes/_authenticated/account.requests.new'
import { Route as AuthenticatedAccountRequestsIdRouteImport } from './routes/_authenticated/account.requests.$id'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSolutionsRoute = BusinessSolutionsRouteImport.update({
  id: '/business-solutions',
  path: '/business-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ServicesCustomAquariumsRoute = ServicesCustomAquariumsRouteImport.update({
  id: '/custom-aquariums',
  path: '/custom-aquariums',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTanksRoute = AuthenticatedAdminTanksRouteImport.update({
  id: '/tanks',
  path: '/tanks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectCategoriesRoute =
  AuthenticatedAdminProjectCategoriesRouteImport.update({
    id: '/project-categories',
    path: '/project-categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDesignRoute =
  AuthenticatedAdminDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountRequestsRoute =
  AuthenticatedAccountRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountReportsRoute =
  AuthenticatedAccountReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAppointmentsRoute =
  AuthenticatedAccountAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminRequestsIndexRoute =
  AuthenticatedAdminRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminRequestsRoute,
  } as any)
const AuthenticatedAdminGalleryIndexRoute =
  AuthenticatedAdminGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceIndexRoute =
  AuthenticatedAdminFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminDesignIndexRoute =
  AuthenticatedAdminDesignIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAccountTanksIndexRoute =
  AuthenticatedAccountTanksIndexRouteImport.update({
    id: '/tanks/',
    path: '/tanks/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountRequestsIndexRoute =
  AuthenticatedAccountRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRequestsRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminTanksIdRoute =
  AuthenticatedAdminTanksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTanksRoute,
  } as any)
const AuthenticatedAdminRequestsIdRoute =
  AuthenticatedAdminRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRequestsRoute,
  } as any)
const AuthenticatedAdminFinanceSuppliersRoute =
  AuthenticatedAdminFinanceSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceSettingsRoute =
  AuthenticatedAdminFinanceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceIncomesRoute =
  AuthenticatedAdminFinanceIncomesRouteImport.update({
    id: '/incomes',
    path: '/incomes',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceExportRoute =
  AuthenticatedAdminFinanceExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceExpensesRoute =
  AuthenticatedAdminFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceCategoriesRoute =
  AuthenticatedAdminFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceAuditRoute =
  AuthenticatedAdminFinanceAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminFinanceAttachmentsRoute =
  AuthenticatedAdminFinanceAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthenticatedAdminFinanceRoute,
  } as any)
const AuthenticatedAdminDesignContactRoute =
  AuthenticatedAdminDesignContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAdminDesignAboutRoute =
  AuthenticatedAdminDesignAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAccountTanksIdRoute =
  AuthenticatedAccountTanksIdRouteImport.update({
    id: '/tanks/$id',
    path: '/tanks/$id',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountRequestsNewRoute =
  AuthenticatedAccountRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountRequestsRoute,
  } as any)
const AuthenticatedAccountRequestsIdRoute =
  AuthenticatedAccountRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAccountRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/custom-aquariums': typeof ServicesCustomAquariumsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reports': typeof AuthenticatedAccountReportsRoute
  '/account/requests': typeof AuthenticatedAccountRequestsRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/design': typeof AuthenticatedAdminDesignRouteWithChildren
  '/admin/finance': typeof AuthenticatedAdminFinanceRouteWithChildren
  '/admin/project-categories': typeof AuthenticatedAdminProjectCategoriesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRouteWithChildren
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tanks': typeof AuthenticatedAdminTanksRouteWithChildren
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/requests/$id': typeof AuthenticatedAccountRequestsIdRoute
  '/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/admin/finance/attachments': typeof AuthenticatedAdminFinanceAttachmentsRoute
  '/admin/finance/audit': typeof AuthenticatedAdminFinanceAuditRoute
  '/admin/finance/categories': typeof AuthenticatedAdminFinanceCategoriesRoute
  '/admin/finance/expenses': typeof AuthenticatedAdminFinanceExpensesRoute
  '/admin/finance/export': typeof AuthenticatedAdminFinanceExportRoute
  '/admin/finance/incomes': typeof AuthenticatedAdminFinanceIncomesRoute
  '/admin/finance/settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/finance/suppliers': typeof AuthenticatedAdminFinanceSuppliersRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/tanks/$id': typeof AuthenticatedAdminTanksIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/account/requests/': typeof AuthenticatedAccountRequestsIndexRoute
  '/account/tanks/': typeof AuthenticatedAccountTanksIndexRoute
  '/admin/design/': typeof AuthenticatedAdminDesignIndexRoute
  '/admin/finance/': typeof AuthenticatedAdminFinanceIndexRoute
  '/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/custom-aquariums': typeof ServicesCustomAquariumsRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/services': typeof ServicesIndexRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reports': typeof AuthenticatedAccountReportsRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/project-categories': typeof AuthenticatedAdminProjectCategoriesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tanks': typeof AuthenticatedAdminTanksRouteWithChildren
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/requests/$id': typeof AuthenticatedAccountRequestsIdRoute
  '/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/admin/finance/attachments': typeof AuthenticatedAdminFinanceAttachmentsRoute
  '/admin/finance/audit': typeof AuthenticatedAdminFinanceAuditRoute
  '/admin/finance/categories': typeof AuthenticatedAdminFinanceCategoriesRoute
  '/admin/finance/expenses': typeof AuthenticatedAdminFinanceExpensesRoute
  '/admin/finance/export': typeof AuthenticatedAdminFinanceExportRoute
  '/admin/finance/incomes': typeof AuthenticatedAdminFinanceIncomesRoute
  '/admin/finance/settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/finance/suppliers': typeof AuthenticatedAdminFinanceSuppliersRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/tanks/$id': typeof AuthenticatedAdminTanksIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/account/requests': typeof AuthenticatedAccountRequestsIndexRoute
  '/account/tanks': typeof AuthenticatedAccountTanksIndexRoute
  '/admin/design': typeof AuthenticatedAdminDesignIndexRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceIndexRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryIndexRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-solutions': typeof BusinessSolutionsRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/custom-aquariums': typeof ServicesCustomAquariumsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/reports': typeof AuthenticatedAccountReportsRoute
  '/_authenticated/account/requests': typeof AuthenticatedAccountRequestsRouteWithChildren
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/design': typeof AuthenticatedAdminDesignRouteWithChildren
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRouteWithChildren
  '/_authenticated/admin/project-categories': typeof AuthenticatedAdminProjectCategoriesRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRouteWithChildren
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tanks': typeof AuthenticatedAdminTanksRouteWithChildren
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/requests/$id': typeof AuthenticatedAccountRequestsIdRoute
  '/_authenticated/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/_authenticated/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/_authenticated/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/_authenticated/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/_authenticated/admin/finance/attachments': typeof AuthenticatedAdminFinanceAttachmentsRoute
  '/_authenticated/admin/finance/audit': typeof AuthenticatedAdminFinanceAuditRoute
  '/_authenticated/admin/finance/categories': typeof AuthenticatedAdminFinanceCategoriesRoute
  '/_authenticated/admin/finance/expenses': typeof AuthenticatedAdminFinanceExpensesRoute
  '/_authenticated/admin/finance/export': typeof AuthenticatedAdminFinanceExportRoute
  '/_authenticated/admin/finance/incomes': typeof AuthenticatedAdminFinanceIncomesRoute
  '/_authenticated/admin/finance/settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/_authenticated/admin/finance/suppliers': typeof AuthenticatedAdminFinanceSuppliersRoute
  '/_authenticated/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/_authenticated/admin/tanks/$id': typeof AuthenticatedAdminTanksIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/account/requests/': typeof AuthenticatedAccountRequestsIndexRoute
  '/_authenticated/account/tanks/': typeof AuthenticatedAccountTanksIndexRoute
  '/_authenticated/admin/design/': typeof AuthenticatedAdminDesignIndexRoute
  '/_authenticated/admin/finance/': typeof AuthenticatedAdminFinanceIndexRoute
  '/_authenticated/admin/gallery/': typeof AuthenticatedAdminGalleryIndexRoute
  '/_authenticated/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/knowledge'
    | '/maintenance'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/trust'
    | '/account'
    | '/admin'
    | '/knowledge/$slug'
    | '/services/$slug'
    | '/services/custom-aquariums'
    | '/knowledge/'
    | '/services/'
    | '/account/appointments'
    | '/account/notifications'
    | '/account/profile'
    | '/account/reports'
    | '/account/requests'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/design'
    | '/admin/finance'
    | '/admin/project-categories'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/tanks'
    | '/admin/testimonials'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/requests/$id'
    | '/account/requests/new'
    | '/account/tanks/$id'
    | '/admin/design/about'
    | '/admin/design/contact'
    | '/admin/finance/attachments'
    | '/admin/finance/audit'
    | '/admin/finance/categories'
    | '/admin/finance/expenses'
    | '/admin/finance/export'
    | '/admin/finance/incomes'
    | '/admin/finance/settings'
    | '/admin/finance/suppliers'
    | '/admin/requests/$id'
    | '/admin/tanks/$id'
    | '/admin/users/$id'
    | '/account/requests/'
    | '/account/tanks/'
    | '/admin/design/'
    | '/admin/finance/'
    | '/admin/gallery/'
    | '/admin/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/maintenance'
    | '/portfolio'
    | '/sitemap.xml'
    | '/trust'
    | '/knowledge/$slug'
    | '/services/$slug'
    | '/services/custom-aquariums'
    | '/knowledge'
    | '/services'
    | '/account/appointments'
    | '/account/notifications'
    | '/account/profile'
    | '/account/reports'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/project-categories'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/tanks'
    | '/admin/testimonials'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/account/requests/$id'
    | '/account/requests/new'
    | '/account/tanks/$id'
    | '/admin/design/about'
    | '/admin/design/contact'
    | '/admin/finance/attachments'
    | '/admin/finance/audit'
    | '/admin/finance/categories'
    | '/admin/finance/expenses'
    | '/admin/finance/export'
    | '/admin/finance/incomes'
    | '/admin/finance/settings'
    | '/admin/finance/suppliers'
    | '/admin/requests/$id'
    | '/admin/tanks/$id'
    | '/admin/users/$id'
    | '/account/requests'
    | '/account/tanks'
    | '/admin/design'
    | '/admin/finance'
    | '/admin/gallery'
    | '/admin/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/business-solutions'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/knowledge'
    | '/maintenance'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/trust'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/knowledge/$slug'
    | '/services/$slug'
    | '/services/custom-aquariums'
    | '/knowledge/'
    | '/services/'
    | '/_authenticated/account/appointments'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/reports'
    | '/_authenticated/account/requests'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/design'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/project-categories'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tanks'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/users'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/account/requests/$id'
    | '/_authenticated/account/requests/new'
    | '/_authenticated/account/tanks/$id'
    | '/_authenticated/admin/design/about'
    | '/_authenticated/admin/design/contact'
    | '/_authenticated/admin/finance/attachments'
    | '/_authenticated/admin/finance/audit'
    | '/_authenticated/admin/finance/categories'
    | '/_authenticated/admin/finance/expenses'
    | '/_authenticated/admin/finance/export'
    | '/_authenticated/admin/finance/incomes'
    | '/_authenticated/admin/finance/settings'
    | '/_authenticated/admin/finance/suppliers'
    | '/_authenticated/admin/requests/$id'
    | '/_authenticated/admin/tanks/$id'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/account/requests/'
    | '/_authenticated/account/tanks/'
    | '/_authenticated/admin/design/'
    | '/_authenticated/admin/finance/'
    | '/_authenticated/admin/gallery/'
    | '/_authenticated/admin/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BusinessSolutionsRoute: typeof BusinessSolutionsRoute
  CatalogRoute: typeof CatalogRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-solutions': {
      id: '/business-solutions'
      path: '/business-solutions'
      fullPath: '/business-solutions'
      preLoaderRoute: typeof BusinessSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/services/custom-aquariums': {
      id: '/services/custom-aquariums'
      path: '/custom-aquariums'
      fullPath: '/services/custom-aquariums'
      preLoaderRoute: typeof ServicesCustomAquariumsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tanks': {
      id: '/_authenticated/admin/tanks'
      path: '/tanks'
      fullPath: '/admin/tanks'
      preLoaderRoute: typeof AuthenticatedAdminTanksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/project-categories': {
      id: '/_authenticated/admin/project-categories'
      path: '/project-categories'
      fullPath: '/admin/project-categories'
      preLoaderRoute: typeof AuthenticatedAdminProjectCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/design': {
      id: '/_authenticated/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AuthenticatedAdminDesignRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/requests': {
      id: '/_authenticated/account/requests'
      path: '/requests'
      fullPath: '/account/requests'
      preLoaderRoute: typeof AuthenticatedAccountRequestsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/reports': {
      id: '/_authenticated/account/reports'
      path: '/reports'
      fullPath: '/account/reports'
      preLoaderRoute: typeof AuthenticatedAccountReportsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/appointments': {
      id: '/_authenticated/account/appointments'
      path: '/appointments'
      fullPath: '/account/appointments'
      preLoaderRoute: typeof AuthenticatedAccountAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/requests/': {
      id: '/_authenticated/admin/requests/'
      path: '/'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRequestsRoute
    }
    '/_authenticated/admin/gallery/': {
      id: '/_authenticated/admin/gallery/'
      path: '/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AuthenticatedAdminGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance/': {
      id: '/_authenticated/admin/finance/'
      path: '/'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AuthenticatedAdminFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/design/': {
      id: '/_authenticated/admin/design/'
      path: '/'
      fullPath: '/admin/design/'
      preLoaderRoute: typeof AuthenticatedAdminDesignIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/account/tanks/': {
      id: '/_authenticated/account/tanks/'
      path: '/tanks'
      fullPath: '/account/tanks/'
      preLoaderRoute: typeof AuthenticatedAccountTanksIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/requests/': {
      id: '/_authenticated/account/requests/'
      path: '/'
      fullPath: '/account/requests/'
      preLoaderRoute: typeof AuthenticatedAccountRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRequestsRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/tanks/$id': {
      id: '/_authenticated/admin/tanks/$id'
      path: '/$id'
      fullPath: '/admin/tanks/$id'
      preLoaderRoute: typeof AuthenticatedAdminTanksIdRouteImport
      parentRoute: typeof AuthenticatedAdminTanksRoute
    }
    '/_authenticated/admin/requests/$id': {
      id: '/_authenticated/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRequestsRoute
    }
    '/_authenticated/admin/finance/suppliers': {
      id: '/_authenticated/admin/finance/suppliers'
      path: '/suppliers'
      fullPath: '/admin/finance/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminFinanceSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/settings': {
      id: '/_authenticated/admin/finance/settings'
      path: '/settings'
      fullPath: '/admin/finance/settings'
      preLoaderRoute: typeof AuthenticatedAdminFinanceSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/incomes': {
      id: '/_authenticated/admin/finance/incomes'
      path: '/incomes'
      fullPath: '/admin/finance/incomes'
      preLoaderRoute: typeof AuthenticatedAdminFinanceIncomesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/export': {
      id: '/_authenticated/admin/finance/export'
      path: '/export'
      fullPath: '/admin/finance/export'
      preLoaderRoute: typeof AuthenticatedAdminFinanceExportRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/expenses': {
      id: '/_authenticated/admin/finance/expenses'
      path: '/expenses'
      fullPath: '/admin/finance/expenses'
      preLoaderRoute: typeof AuthenticatedAdminFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/categories': {
      id: '/_authenticated/admin/finance/categories'
      path: '/categories'
      fullPath: '/admin/finance/categories'
      preLoaderRoute: typeof AuthenticatedAdminFinanceCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/audit': {
      id: '/_authenticated/admin/finance/audit'
      path: '/audit'
      fullPath: '/admin/finance/audit'
      preLoaderRoute: typeof AuthenticatedAdminFinanceAuditRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/finance/attachments': {
      id: '/_authenticated/admin/finance/attachments'
      path: '/attachments'
      fullPath: '/admin/finance/attachments'
      preLoaderRoute: typeof AuthenticatedAdminFinanceAttachmentsRouteImport
      parentRoute: typeof AuthenticatedAdminFinanceRoute
    }
    '/_authenticated/admin/design/contact': {
      id: '/_authenticated/admin/design/contact'
      path: '/contact'
      fullPath: '/admin/design/contact'
      preLoaderRoute: typeof AuthenticatedAdminDesignContactRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/admin/design/about': {
      id: '/_authenticated/admin/design/about'
      path: '/about'
      fullPath: '/admin/design/about'
      preLoaderRoute: typeof AuthenticatedAdminDesignAboutRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/account/tanks/$id': {
      id: '/_authenticated/account/tanks/$id'
      path: '/tanks/$id'
      fullPath: '/account/tanks/$id'
      preLoaderRoute: typeof AuthenticatedAccountTanksIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/requests/new': {
      id: '/_authenticated/account/requests/new'
      path: '/new'
      fullPath: '/account/requests/new'
      preLoaderRoute: typeof AuthenticatedAccountRequestsNewRouteImport
      parentRoute: typeof AuthenticatedAccountRequestsRoute
    }
    '/_authenticated/account/requests/$id': {
      id: '/_authenticated/account/requests/$id'
      path: '/$id'
      fullPath: '/account/requests/$id'
      preLoaderRoute: typeof AuthenticatedAccountRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAccountRequestsRoute
    }
  }
}

interface AuthenticatedAccountRequestsRouteChildren {
  AuthenticatedAccountRequestsIdRoute: typeof AuthenticatedAccountRequestsIdRoute
  AuthenticatedAccountRequestsNewRoute: typeof AuthenticatedAccountRequestsNewRoute
  AuthenticatedAccountRequestsIndexRoute: typeof AuthenticatedAccountRequestsIndexRoute
}

const AuthenticatedAccountRequestsRouteChildren: AuthenticatedAccountRequestsRouteChildren =
  {
    AuthenticatedAccountRequestsIdRoute: AuthenticatedAccountRequestsIdRoute,
    AuthenticatedAccountRequestsNewRoute: AuthenticatedAccountRequestsNewRoute,
    AuthenticatedAccountRequestsIndexRoute:
      AuthenticatedAccountRequestsIndexRoute,
  }

const AuthenticatedAccountRequestsRouteWithChildren =
  AuthenticatedAccountRequestsRoute._addFileChildren(
    AuthenticatedAccountRequestsRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAppointmentsRoute: typeof AuthenticatedAccountAppointmentsRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountReportsRoute: typeof AuthenticatedAccountReportsRoute
  AuthenticatedAccountRequestsRoute: typeof AuthenticatedAccountRequestsRouteWithChildren
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountTanksIdRoute: typeof AuthenticatedAccountTanksIdRoute
  AuthenticatedAccountTanksIndexRoute: typeof AuthenticatedAccountTanksIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAppointmentsRoute: AuthenticatedAccountAppointmentsRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountReportsRoute: AuthenticatedAccountReportsRoute,
  AuthenticatedAccountRequestsRoute:
    AuthenticatedAccountRequestsRouteWithChildren,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountTanksIdRoute: AuthenticatedAccountTanksIdRoute,
  AuthenticatedAccountTanksIndexRoute: AuthenticatedAccountTanksIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminDesignRouteChildren {
  AuthenticatedAdminDesignAboutRoute: typeof AuthenticatedAdminDesignAboutRoute
  AuthenticatedAdminDesignContactRoute: typeof AuthenticatedAdminDesignContactRoute
  AuthenticatedAdminDesignIndexRoute: typeof AuthenticatedAdminDesignIndexRoute
}

const AuthenticatedAdminDesignRouteChildren: AuthenticatedAdminDesignRouteChildren =
  {
    AuthenticatedAdminDesignAboutRoute: AuthenticatedAdminDesignAboutRoute,
    AuthenticatedAdminDesignContactRoute: AuthenticatedAdminDesignContactRoute,
    AuthenticatedAdminDesignIndexRoute: AuthenticatedAdminDesignIndexRoute,
  }

const AuthenticatedAdminDesignRouteWithChildren =
  AuthenticatedAdminDesignRoute._addFileChildren(
    AuthenticatedAdminDesignRouteChildren,
  )

interface AuthenticatedAdminFinanceRouteChildren {
  AuthenticatedAdminFinanceAttachmentsRoute: typeof AuthenticatedAdminFinanceAttachmentsRoute
  AuthenticatedAdminFinanceAuditRoute: typeof AuthenticatedAdminFinanceAuditRoute
  AuthenticatedAdminFinanceCategoriesRoute: typeof AuthenticatedAdminFinanceCategoriesRoute
  AuthenticatedAdminFinanceExpensesRoute: typeof AuthenticatedAdminFinanceExpensesRoute
  AuthenticatedAdminFinanceExportRoute: typeof AuthenticatedAdminFinanceExportRoute
  AuthenticatedAdminFinanceIncomesRoute: typeof AuthenticatedAdminFinanceIncomesRoute
  AuthenticatedAdminFinanceSettingsRoute: typeof AuthenticatedAdminFinanceSettingsRoute
  AuthenticatedAdminFinanceSuppliersRoute: typeof AuthenticatedAdminFinanceSuppliersRoute
  AuthenticatedAdminFinanceIndexRoute: typeof AuthenticatedAdminFinanceIndexRoute
}

const AuthenticatedAdminFinanceRouteChildren: AuthenticatedAdminFinanceRouteChildren =
  {
    AuthenticatedAdminFinanceAttachmentsRoute:
      AuthenticatedAdminFinanceAttachmentsRoute,
    AuthenticatedAdminFinanceAuditRoute: AuthenticatedAdminFinanceAuditRoute,
    AuthenticatedAdminFinanceCategoriesRoute:
      AuthenticatedAdminFinanceCategoriesRoute,
    AuthenticatedAdminFinanceExpensesRoute:
      AuthenticatedAdminFinanceExpensesRoute,
    AuthenticatedAdminFinanceExportRoute: AuthenticatedAdminFinanceExportRoute,
    AuthenticatedAdminFinanceIncomesRoute:
      AuthenticatedAdminFinanceIncomesRoute,
    AuthenticatedAdminFinanceSettingsRoute:
      AuthenticatedAdminFinanceSettingsRoute,
    AuthenticatedAdminFinanceSuppliersRoute:
      AuthenticatedAdminFinanceSuppliersRoute,
    AuthenticatedAdminFinanceIndexRoute: AuthenticatedAdminFinanceIndexRoute,
  }

const AuthenticatedAdminFinanceRouteWithChildren =
  AuthenticatedAdminFinanceRoute._addFileChildren(
    AuthenticatedAdminFinanceRouteChildren,
  )

interface AuthenticatedAdminRequestsRouteChildren {
  AuthenticatedAdminRequestsIdRoute: typeof AuthenticatedAdminRequestsIdRoute
  AuthenticatedAdminRequestsIndexRoute: typeof AuthenticatedAdminRequestsIndexRoute
}

const AuthenticatedAdminRequestsRouteChildren: AuthenticatedAdminRequestsRouteChildren =
  {
    AuthenticatedAdminRequestsIdRoute: AuthenticatedAdminRequestsIdRoute,
    AuthenticatedAdminRequestsIndexRoute: AuthenticatedAdminRequestsIndexRoute,
  }

const AuthenticatedAdminRequestsRouteWithChildren =
  AuthenticatedAdminRequestsRoute._addFileChildren(
    AuthenticatedAdminRequestsRouteChildren,
  )

interface AuthenticatedAdminTanksRouteChildren {
  AuthenticatedAdminTanksIdRoute: typeof AuthenticatedAdminTanksIdRoute
}

const AuthenticatedAdminTanksRouteChildren: AuthenticatedAdminTanksRouteChildren =
  {
    AuthenticatedAdminTanksIdRoute: AuthenticatedAdminTanksIdRoute,
  }

const AuthenticatedAdminTanksRouteWithChildren =
  AuthenticatedAdminTanksRoute._addFileChildren(
    AuthenticatedAdminTanksRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminDesignRoute: typeof AuthenticatedAdminDesignRouteWithChildren
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRouteWithChildren
  AuthenticatedAdminProjectCategoriesRoute: typeof AuthenticatedAdminProjectCategoriesRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRouteWithChildren
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTanksRoute: typeof AuthenticatedAdminTanksRouteWithChildren
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminGalleryIndexRoute: typeof AuthenticatedAdminGalleryIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminDesignRoute: AuthenticatedAdminDesignRouteWithChildren,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRouteWithChildren,
  AuthenticatedAdminProjectCategoriesRoute:
    AuthenticatedAdminProjectCategoriesRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRouteWithChildren,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTanksRoute: AuthenticatedAdminTanksRouteWithChildren,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminGalleryIndexRoute: AuthenticatedAdminGalleryIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesCustomAquariumsRoute: typeof ServicesCustomAquariumsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesCustomAquariumsRoute: ServicesCustomAquariumsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BusinessSolutionsRoute: BusinessSolutionsRoute,
  CatalogRoute: CatalogRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
