/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminDesignRouteImport } from './routes/_authenticated/admin.design'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAccountTanksRouteImport } from './routes/_authenticated/account.tanks'
import { Route as AuthenticatedAccountRequestsRouteImport } from './routes/_authenticated/account.requests'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountAppointmentsRouteImport } from './routes/_authenticated/account.appointments'
import { Route as AuthenticatedAdminDesignIndexRouteImport } from './routes/_authenticated/admin.design.index'
import { Route as AuthenticatedAdminDesignContactRouteImport } from './routes/_authenticated/admin.design.contact'
import { Route as AuthenticatedAdminDesignAboutRouteImport } from './routes/_authenticated/admin.design.about'
import { Route as AuthenticatedAccountTanksIdRouteImport } from './routes/_authenticated/account.tanks.$id'
import { Route as AuthenticatedAccountRequestsNewRouteImport } from './routes/_authenticated/account.requests.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDesignRoute =
  AuthenticatedAdminDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountTanksRoute =
  AuthenticatedAccountTanksRouteImport.update({
    id: '/tanks',
    path: '/tanks',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountRequestsRoute =
  AuthenticatedAccountRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAppointmentsRoute =
  AuthenticatedAccountAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminDesignIndexRoute =
  AuthenticatedAdminDesignIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAdminDesignContactRoute =
  AuthenticatedAdminDesignContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAdminDesignAboutRoute =
  AuthenticatedAdminDesignAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedAdminDesignRoute,
  } as any)
const AuthenticatedAccountTanksIdRoute =
  AuthenticatedAccountTanksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAccountTanksRoute,
  } as any)
const AuthenticatedAccountRequestsNewRoute =
  AuthenticatedAccountRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/requests': typeof AuthenticatedAccountRequestsRouteWithChildren
  '/account/tanks': typeof AuthenticatedAccountTanksRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/design': typeof AuthenticatedAdminDesignRouteWithChildren
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/admin/design/': typeof AuthenticatedAdminDesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/requests': typeof AuthenticatedAccountRequestsRouteWithChildren
  '/account/tanks': typeof AuthenticatedAccountTanksRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/admin/design': typeof AuthenticatedAdminDesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/_authenticated/account/appointments': typeof AuthenticatedAccountAppointmentsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/requests': typeof AuthenticatedAccountRequestsRouteWithChildren
  '/_authenticated/account/tanks': typeof AuthenticatedAccountTanksRouteWithChildren
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/design': typeof AuthenticatedAdminDesignRouteWithChildren
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/requests/new': typeof AuthenticatedAccountRequestsNewRoute
  '/_authenticated/account/tanks/$id': typeof AuthenticatedAccountTanksIdRoute
  '/_authenticated/admin/design/about': typeof AuthenticatedAdminDesignAboutRoute
  '/_authenticated/admin/design/contact': typeof AuthenticatedAdminDesignContactRoute
  '/_authenticated/admin/design/': typeof AuthenticatedAdminDesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/knowledge'
    | '/maintenance'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/account/appointments'
    | '/account/profile'
    | '/account/requests'
    | '/account/tanks'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/design'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/requests/new'
    | '/account/tanks/$id'
    | '/admin/design/about'
    | '/admin/design/contact'
    | '/admin/design/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/maintenance'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/knowledge/$slug'
    | '/knowledge'
    | '/account/appointments'
    | '/account/profile'
    | '/account/requests'
    | '/account/tanks'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/account/requests/new'
    | '/account/tanks/$id'
    | '/admin/design/about'
    | '/admin/design/contact'
    | '/admin/design'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/consultation'
    | '/contact'
    | '/knowledge'
    | '/maintenance'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/_authenticated/account/appointments'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/requests'
    | '/_authenticated/account/tanks'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/design'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/users'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/account/requests/new'
    | '/_authenticated/account/tanks/$id'
    | '/_authenticated/admin/design/about'
    | '/_authenticated/admin/design/contact'
    | '/_authenticated/admin/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/design': {
      id: '/_authenticated/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AuthenticatedAdminDesignRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/tanks': {
      id: '/_authenticated/account/tanks'
      path: '/tanks'
      fullPath: '/account/tanks'
      preLoaderRoute: typeof AuthenticatedAccountTanksRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/requests': {
      id: '/_authenticated/account/requests'
      path: '/requests'
      fullPath: '/account/requests'
      preLoaderRoute: typeof AuthenticatedAccountRequestsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/appointments': {
      id: '/_authenticated/account/appointments'
      path: '/appointments'
      fullPath: '/account/appointments'
      preLoaderRoute: typeof AuthenticatedAccountAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/design/': {
      id: '/_authenticated/admin/design/'
      path: '/'
      fullPath: '/admin/design/'
      preLoaderRoute: typeof AuthenticatedAdminDesignIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/admin/design/contact': {
      id: '/_authenticated/admin/design/contact'
      path: '/contact'
      fullPath: '/admin/design/contact'
      preLoaderRoute: typeof AuthenticatedAdminDesignContactRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/admin/design/about': {
      id: '/_authenticated/admin/design/about'
      path: '/about'
      fullPath: '/admin/design/about'
      preLoaderRoute: typeof AuthenticatedAdminDesignAboutRouteImport
      parentRoute: typeof AuthenticatedAdminDesignRoute
    }
    '/_authenticated/account/tanks/$id': {
      id: '/_authenticated/account/tanks/$id'
      path: '/$id'
      fullPath: '/account/tanks/$id'
      preLoaderRoute: typeof AuthenticatedAccountTanksIdRouteImport
      parentRoute: typeof AuthenticatedAccountTanksRoute
    }
    '/_authenticated/account/requests/new': {
      id: '/_authenticated/account/requests/new'
      path: '/new'
      fullPath: '/account/requests/new'
      preLoaderRoute: typeof AuthenticatedAccountRequestsNewRouteImport
      parentRoute: typeof AuthenticatedAccountRequestsRoute
    }
  }
}

interface AuthenticatedAccountRequestsRouteChildren {
  AuthenticatedAccountRequestsNewRoute: typeof AuthenticatedAccountRequestsNewRoute
}

const AuthenticatedAccountRequestsRouteChildren: AuthenticatedAccountRequestsRouteChildren =
  {
    AuthenticatedAccountRequestsNewRoute: AuthenticatedAccountRequestsNewRoute,
  }

const AuthenticatedAccountRequestsRouteWithChildren =
  AuthenticatedAccountRequestsRoute._addFileChildren(
    AuthenticatedAccountRequestsRouteChildren,
  )

interface AuthenticatedAccountTanksRouteChildren {
  AuthenticatedAccountTanksIdRoute: typeof AuthenticatedAccountTanksIdRoute
}

const AuthenticatedAccountTanksRouteChildren: AuthenticatedAccountTanksRouteChildren =
  {
    AuthenticatedAccountTanksIdRoute: AuthenticatedAccountTanksIdRoute,
  }

const AuthenticatedAccountTanksRouteWithChildren =
  AuthenticatedAccountTanksRoute._addFileChildren(
    AuthenticatedAccountTanksRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAppointmentsRoute: typeof AuthenticatedAccountAppointmentsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountRequestsRoute: typeof AuthenticatedAccountRequestsRouteWithChildren
  AuthenticatedAccountTanksRoute: typeof AuthenticatedAccountTanksRouteWithChildren
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAppointmentsRoute: AuthenticatedAccountAppointmentsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountRequestsRoute:
    AuthenticatedAccountRequestsRouteWithChildren,
  AuthenticatedAccountTanksRoute: AuthenticatedAccountTanksRouteWithChildren,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminDesignRouteChildren {
  AuthenticatedAdminDesignAboutRoute: typeof AuthenticatedAdminDesignAboutRoute
  AuthenticatedAdminDesignContactRoute: typeof AuthenticatedAdminDesignContactRoute
  AuthenticatedAdminDesignIndexRoute: typeof AuthenticatedAdminDesignIndexRoute
}

const AuthenticatedAdminDesignRouteChildren: AuthenticatedAdminDesignRouteChildren =
  {
    AuthenticatedAdminDesignAboutRoute: AuthenticatedAdminDesignAboutRoute,
    AuthenticatedAdminDesignContactRoute: AuthenticatedAdminDesignContactRoute,
    AuthenticatedAdminDesignIndexRoute: AuthenticatedAdminDesignIndexRoute,
  }

const AuthenticatedAdminDesignRouteWithChildren =
  AuthenticatedAdminDesignRoute._addFileChildren(
    AuthenticatedAdminDesignRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminDesignRoute: typeof AuthenticatedAdminDesignRouteWithChildren
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminDesignRoute: AuthenticatedAdminDesignRouteWithChildren,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
