
ALTER TABLE public.services
  ADD COLUMN IF NOT EXISTS short_description text,
  ADD COLUMN IF NOT EXISTS full_description text,
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS service_type text,
  ADD COLUMN IF NOT EXISTS price_label text,
  ADD COLUMN IF NOT EXISTS starting_price numeric,
  ADD COLUMN IF NOT EXISTS includes jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS suitable_for jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS process_steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faqs jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS cta_label text,
  ADD COLUMN IF NOT EXISTS cta_type text DEFAULT 'whatsapp',
  ADD COLUMN IF NOT EXISTS cta_url text,
  ADD COLUMN IF NOT EXISTS linked_page_type text NOT NULL DEFAULT 'custom_service_page',
  ADD COLUMN IF NOT EXISTS linked_page_url text,
  ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS meta_title text,
  ADD COLUMN IF NOT EXISTS meta_description text;

-- Seed defaults
INSERT INTO public.services (slug, title, short_description, icon, category, linked_page_type, linked_page_url, includes, suitable_for, is_featured, published, sort_order, cta_label)
VALUES
  ('custom-aquariums', 'تصميم وتركيب أحواض مخصصة',
    'نصمم وننفذ أحواض مائية حسب مساحتك وذوقك، من الفكرة حتى التشغيل.',
    'Fish', 'تصميم وتركيب', 'custom_service_page', NULL,
    '["استشارة مبدئية","اقتراح تصميم مناسب","اختيار الحوض والمعدات","تجهيز الديكور الداخلي","تركيب الفلترة والإضاءة","تشغيل النظام","إرشادات العناية بعد التسليم"]'::jsonb,
    '["المنازل","المكاتب","المجالس","غرف المعيشة","العملاء الجدد","من يريد حوضًا جاهزًا بدون تعقيد"]'::jsonb,
    true, true, 10, 'اطلب الخدمة'),
  ('maintenance', 'صيانة أحواض مائية',
    'صيانة دورية أو طارئة للحفاظ على صفاء الماء وصحة الأسماك واستقرار الحوض.',
    'Wrench', 'صيانة', 'existing_page', '/maintenance',
    '[]'::jsonb, '[]'::jsonb, true, true, 20, 'باقات الصيانة'),
  ('aquarium-consultation', 'استشارات مشاكل الأحواض',
    'استشارة لحل مشاكل الماء، الأسماك، الطحالب، الفلاتر، أو اختيار التجهيز المناسب.',
    'MessagesSquare', 'استشارات', 'custom_service_page', NULL,
    '["مراجعة صور أو فيديو للحوض","تحليل المشكلة مبدئيًا","توصيات علاجية أو تشغيلية","خطة خطوات واضحة","اقتراح منتجات مناسبة إذا لزم"]'::jsonb,
    '["ماء عكر","موت أسماك","طحالب","رائحة","سمكة مريضة","حوض جديد غير مستقر","اختيار فلتر أو إضاءة"]'::jsonb,
    true, true, 30, 'احجز استشارة'),
  ('business-solutions', 'حلول الأعمال والمشاريع التجارية',
    'أحواض مائية مخصصة للكافيهات والمطاعم والمكاتب والعيادات والمعارض.',
    'Building2', 'مشاريع تجارية', 'existing_page', '/business-solutions',
    '[]'::jsonb, '[]'::jsonb, true, true, 40, 'استعرض الحلول'),
  ('livestock-supplies', 'توريد وتجهيز كائنات ومستلزمات',
    'نوفر أسماكًا، نباتات، معدات، ومواد تشغيل مناسبة للحوض حسب نوع النظام.',
    'Sparkles', 'مستلزمات', 'existing_page', '/catalog',
    '[]'::jsonb, '[]'::jsonb, false, true, 50, 'تصفح الكاتلوج'),
  ('aquascape-design', 'تصميم أكواسكيب وديكور داخلي',
    'تصميم ديكور داخلي للحوض باستخدام الصخور، الأخشاب، النباتات، والرؤية الجمالية المناسبة.',
    'Sparkles', 'تصميم', 'custom_service_page', NULL,
    '[]'::jsonb, '[]'::jsonb, false, true, 60, 'اطلب التصميم'),
  ('marine-reef-tanks', 'تجهيز أحواض بحرية ونانو ريف',
    'تصميم وتجهيز أحواض بحرية ونانو ريف باختيار مناسب للمعدات والكائنات والاستقرار.',
    'Fish', 'بحري', 'custom_service_page', NULL,
    '[]'::jsonb, '[]'::jsonb, false, true, 70, 'اطلب التجهيز'),
  ('aftercare-follow-up', 'متابعة ما بعد التسليم',
    'متابعة إرشادية بعد تركيب الحوض للتأكد من استقرار النظام وفهم العميل لطريقة العناية.',
    'ShieldCheck', 'متابعة', 'custom_service_page', NULL,
    '[]'::jsonb, '[]'::jsonb, false, true, 80, 'اطلب المتابعة')
ON CONFLICT (slug) DO NOTHING;
