
ALTER TABLE public.customer_tanks
  ADD COLUMN IF NOT EXISTS has_protein_skimmer boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS protein_skimmer_model text,
  ADD COLUMN IF NOT EXISTS has_wave_maker boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS wave_maker_model text,
  ADD COLUMN IF NOT EXISTS has_sump boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_ato boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS salt_brand text,
  ADD COLUMN IF NOT EXISTS salinity numeric,
  ADD COLUMN IF NOT EXISTS marine_temperature numeric,
  ADD COLUMN IF NOT EXISTS last_water_change date,
  ADD COLUMN IF NOT EXISTS water_change_percent numeric,
  ADD COLUMN IF NOT EXISTS marine_light_type text,
  ADD COLUMN IF NOT EXISTS white_light_hours numeric,
  ADD COLUMN IF NOT EXISTS blue_light_hours numeric,
  ADD COLUMN IF NOT EXISTS coral_safe_light text,
  ADD COLUMN IF NOT EXISTS has_coral boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS corals jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS test_salinity numeric,
  ADD COLUMN IF NOT EXISTS test_ph numeric,
  ADD COLUMN IF NOT EXISTS test_kh numeric,
  ADD COLUMN IF NOT EXISTS test_calcium numeric,
  ADD COLUMN IF NOT EXISTS test_magnesium numeric,
  ADD COLUMN IF NOT EXISTS test_nitrate numeric,
  ADD COLUMN IF NOT EXISTS test_phosphate numeric,
  ADD COLUMN IF NOT EXISTS test_ammonia numeric,
  ADD COLUMN IF NOT EXISTS test_nitrite numeric,
  ADD COLUMN IF NOT EXISTS tests_updated_at timestamptz;
